### ISSUE TITLE
./bili-cli login不显示二维码

### ISSUE THREAD

**Issue by oarinv** [niuhuan/bili-cli-rs#2]
环境：linux

**Comment by niuhuan** [comment]
有桌面环境吗? 会写入到运行目录里

**Comment by oarinv** [comment]
没有桌面环境，运行目录没找到qr.png，ffmpeg也安装了

**Comment by niuhuan** [comment]
/tmp 目录下会随机生成一个 uuid.png , 桌面环境会自动打开, 非桌面环境您可能需要scp, 或者拷贝配置文件夹到服务器上

**Comment by niuhuan** [comment]
保存cookie的文件名叫properties.db,
 
macos 在 个人文件夹下, "Library",  "Application Support", "bili-cli",

windows 在 个人文件夹下,  "AppData",        "Roaming",       "bili-cli",

linux 在 个人文件夹 下 ".bili-cli",

**Comment by oarinv** [comment]
了解，问题解决

**Comment by niuhuan** [comment]
如果会rust, 可以PR一下, 就给login命令加个 --console 参数, 打印在控制台而不是弹出

https://github.com/timvisee/qr2term-rs

**Comment by rexcape** [comment]
> 如果会rust, 可以PR一下, 就给login命令加个 --console 参数, 打印在控制台而不是弹出
> 
> https://github.com/timvisee/qr2term-rs

正在尝试添加功能

- [x] 为 login 命令添加 --console 参数
- [x] 在 login 函数中识别 --console 参数
- [x] 检测到参数时使用 qr2term-rs 将二维码输出至控制台

**Comment by niuhuan** [comment]
已经在 #3 中被合并
