### ISSUE TITLE
 ./bili-cli user   在登陆后报错

### ISSUE THREAD

**Issue by oarinv** [niuhuan/bili-cli-rs#5]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: data.coins: invalid type: floating point `876.4`, expected i64 at line 1 column 1702

Caused by:
    invalid type: floating point `876.4`, expected i64 at line 1 column 1702', src/main.rs:21:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by oarinv** [comment]
{"code":0,"message":"0","ttl":1,"data":{"mid":32385213,"name":"tragicadg","sex":"男","face":"https://i0.hdslb.com/bfs/face/6e7ee177b5cc681b9609c07f8d5eb574b52d409c.jpg","sign":"","rank":10000,"level":6,"jointime":0,"moral":70,"silence":0,"email_status":1,"tel_status":1,"identification":1,"vip":{"type":1,"status":1,"due_date":1670342400000,"vip_pay_type":0,"theme_type":0,"label":{"path":"","text":"大会员","label_theme":"vip","text_color":"#FFFFFF","bg_style":1,"bg_color":"#FB7299","border_color":"","use_img_label":true,"img_label_uri_hans":"","img_label_uri_hant":"","img_label_uri_hans_static":"https://i0.hdslb.com/bfs/vip/3788b674c69072f1ee252b79a31ecc8c43af3039.png","img_label_uri_hant_static":"https://i0.hdslb.com/bfs/activity-plat/static/20220614/e369244d0b14644f5e1a06431e22a4d5/jwXBWRVwa5.png"},"avatar_subscript":1,"nickname_color":"","role":1,"avatar_subscript_url":"","tv_vip_status":0,"tv_vip_pay_type":0},"pendant":{"pid":0,"name":"","image":"","expire":0,"image_enhance":"","image_enhance_frame":""},"nameplate":{"nid":0,"name":"","image":"","image_small":"","level":"","condition":""},"official":{"role":0,"title":"","desc":"","type":-1},"birthday":940262400,"is_tourist":0,"is_fake_account":0,"pin_prompting":0,"is_deleted":0,"in_reg_audit":0,"is_rip_user":false,"profession":{"id":0,"name":"","show_name":"","is_show":0,"category_one":"","realname":"","title":"","department":""},"face_nft":0,"face_nft_new":0,"is_senior_member":0,"honours":{"mid":32385213,"colour":{"dark":"#CE8620","normal":"#F0900B"},"tags":null},"digital_id":"","digital_type":-2,"level_exp":{"current_level":6,"current_min":28800,"current_exp":29958,"next_exp":-1,"level_up":-62135596800},"coins":876.4,"following":27,"follower":27}}

**Comment by niuhuan** [comment]
已经修复了

**Comment by oarinv** [comment]
好像没有解决

**Comment by niuhuan** [comment]
再试一下，刚才网不好没有push上去

**Comment by oarinv** [comment]
没问题了，非常感谢🙇‍♂
